# create github action to build react app
name: Build
on:
  push:
    branches:
      - main
      - develop
      - feature/*
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        # - name: Deploy
        #     uses: peaceiris/actions-gh-pages@v3
        #     with:
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
        #     publish_dir: ./build